apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-data
  namespace: sentinel
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
