apiVersion: v1
kind: Service
metadata:
  name: langfuse-svc
  namespace: sentinel
  labels:
    app: langfuse
spec:
  selector:
    app: langfuse
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
