apiVersion: v1
kind: Service
metadata:
  name: langfuse-db-svc
  namespace: sentinel
  labels:
    app: langfuse-db
spec:
  selector:
    app: langfuse-db
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
