apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  namespace: sentinel
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
